all: test_L_infty_DT.o

test_L_infty_DT.o : test_L_infty_DT.cpp ../../DCEL/DCEL.h ../../DCEL/Point.h ../../DCEL/Edge.h ../../DCEL/Vector.h
	g++ -o ../test_L_infty_DT.o -c test_L_infty_DT.cpp -std=c++17
